catalog:
  "@antfu/eslint-config": ^4.13.2
  "@changesets/cli": ^2.29.4
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@emotion/css": ^11.13.5
  "@emotion/eslint-plugin": ^11.12.0
  "@eslint/compat": ^1.2.9
  "@eslint/config-inspector": ^1.0.2
  "@eslint-react/eslint-plugin": ^1.50.0
  "@mui/types": ^7.4.2
  "@storybook/preview-api": ^8.6.14
  "@storybook/react": ^9.0.3
  "@tanstack/eslint-plugin-query": ^5.78.0
  "@tanstack/query-core": ^5.79.0
  "@tanstack/react-query": ^5.79.0
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/svelte": ^5.0.4
  "@types/eslint-config-prettier": ^6.11.3
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^13.3.0
  "@types/react": ^19.1.6
  "@vp-tw/tsconfig": ^3.0.0
  commitizen: ^4.3.1
  cspell: ^9.0.2
  es-toolkit: ^1.38.0
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-flat-config-utils: ^2.1.0
  eslint-plugin-mdx: ^3.4.2
  eslint-plugin-package-json: ^0.33.0
  eslint-plugin-react-compiler: ^19.1.0-rc.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.0.3
  eslint-plugin-svelte: ^3.9.0
  eslint-plugin-yml: ^1.18.0
  eslint-typegen: ^2.2.0
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^16.1.0
  local-pkg: ^1.1.1
  npm-run-all: ^4.1.5
  pathe: ^2.0.3
  pkg-dir: ^8.0.0
  prettier: ^3.5.3
  storybook: ^9.0.3
  svelte: ^5.33.11
  tsx: ^4.19.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitest: ^3.1.4

onlyBuiltDependencies:
  - esbuild
  - nx
  - unrs-resolver
overrides:
  "@types/eslint@9": npm:eslint@^9.28.0
packages:
  - packages/*
