catalog:
  "@antfu/eslint-config": ^4.13.0
  "@eslint/compat": ^1.2.9
  "@eslint-react/eslint-plugin": ^1.49.0
  "@mui/types": ^7.2.21
  "@types/eslint-config-prettier": ^6.11.3
  "@types/react": ^19.0.8
  es-toolkit: ^1.37.2
  eslint: ^9.26.0
  eslint-config-prettier: ^10.1.5
  eslint-flat-config-utils: ^2.0.1
  eslint-plugin-mdx: ^3.4.1
  eslint-plugin-package-json: ^0.31.0
  eslint-plugin-react-compiler: ^19.1.0-rc.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^0.12.0
  eslint-plugin-svelte: ^3.5.1
  eslint-plugin-yml: ^1.18.0
  local-pkg: ^1.1.1
  svelte: ^5.28.2
  typescript: ^5.8.3
onlyBuiltDependencies:
  - esbuild
  - nx
  - unrs-resolver
packages:
  - packages/*
