catalog:
  "@antfu/eslint-config": ^4.3.0
  "@eslint/compat": ^1.2.7
  "@eslint-react/eslint-plugin": ^1.29.0
  "@mui/types": ^7.2.21
  "@types/eslint-config-prettier": ^6.11.3
  "@types/react": ^19.0.8
  es-toolkit: ^1.32.0
  eslint: ^9.21.0
  eslint-config-prettier: ^10.0.2
  eslint-flat-config-utils: ^2.0.1
  eslint-plugin-mdx: ^3.1.5
  eslint-plugin-package-json: ^0.26.0
  eslint-plugin-react-compiler: ^19.0.0-beta-e1e972c-20250221
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-storybook: ^0.11.3
  eslint-plugin-svelte: ^3.0.2
  local-pkg: ^1.1.0
  svelte: ^5.20.5
  typescript: ^5.8.2
packages:
  - "packages/*"
