catalog:
  "@antfu/eslint-config": ^7.2.0
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.3.1
  "@commitlint/config-conventional": ^20.3.1
  "@commitlint/types": ^20.3.1
  "@emotion/css": ^11.13.5
  "@emotion/eslint-plugin": ^11.12.0
  "@eslint/compat": ^2.0.1
  "@eslint/config-inspector": ^1.4.2
  "@eslint-react/eslint-plugin": ^2.7.4
  "@mui/types": ^7.4.2
  "@storybook/preview-api": ^8.6.14
  "@storybook/react": ^10.2.1
  "@tanstack/eslint-plugin-query": ^5.91.3
  "@tanstack/react-query": ^5.79.0
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/svelte": ^5.0.4
  "@types/eslint-config-prettier": ^6.11.3
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^14.0.0
  "@types/react": ^19.1.6
  "@typescript/native-preview": ^7.0.0-dev.20251219.1
  "@typescript-eslint/utils": ^8.54.0
  "@vp-tw/tsconfig": ^3.2.1
  commitizen: ^4.3.1
  cspell: ^9.6.2
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-flat-config-utils: ^3.0.0
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-package-json: ^0.88.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  eslint-plugin-storybook: ^10.2.1
  eslint-plugin-svelte: ^3.14.0
  eslint-plugin-yml: ^3.0.0
  eslint-typegen: ^2.2.0
  fast-glob: ^3.3.3
  fs-extra: ^11.3.3
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  local-pkg: ^1.1.2
  npm-run-all: ^4.1.5
  oxfmt: ^0.27.0
  pathe: ^2.0.3
  pkg-dir: ^9.0.0
  storybook: ^10.2.1
  svelte: ^5.48.5
  tsx: ^4.21.0
  typescript: ^5.9.3
  unbuild: ^3.5.0
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
  - nx
  - unrs-resolver

packages:
  - packages/*
shellEmulator: true

trustPolicy: no-downgrade
