catalog:
  "@antfu/eslint-config": 4.10.1
  "@eslint/compat": ^1.2.7
  "@eslint-react/eslint-plugin": ^1.34.0
  "@mui/types": ^7.2.21
  "@types/eslint-config-prettier": ^6.11.3
  "@types/react": ^19.0.8
  es-toolkit: ^1.33.0
  eslint: ^9.22.0
  eslint-config-prettier: ^10.1.1
  eslint-flat-config-utils: ^2.0.1
  eslint-plugin-mdx: ^3.2.0
  eslint-plugin-package-json: ^0.26.3
  eslint-plugin-react-compiler: ^19.0.0-beta-bafa41b-20250307
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-storybook: ^0.11.4
  eslint-plugin-svelte: ^3.1.0
  eslint-plugin-yml: ^1.17.0
  local-pkg: ^1.1.1
  svelte: ^5.23.0
  typescript: ^5.8.2
packages:
  - "packages/*"
